### ISSUE TITLE
Delete ARTIK device on "Manage Artik Devices" page without disconnect

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#106]
**Description of problem:**
If delete ARTIK device on "Manage Artik Devices" page without disconnect, the device info will still remain on the "consoles" panel.

**ARTIK IDE version:** samsung-artik-ide-nightly.zip 2016-08-14 
**ARTIK IDE install directory:** C:\artik-ide-0.1.0-RC3-SNAPSHOT
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + samsung-artik-ide-nightly.zip

**Steps to Reproduce:**
1. Connect ARTIK board to project correctly.
2. Open "Manage Artik Devices" page.
3. Delete the existing connected device without disconnect.
![capture](https://cloud.githubusercontent.com/assets/20865878/17684763/dfad1d8e-6312-11e6-882c-3b7af25a9062.PNG)

**Actual Results:**
The device is still remaining on the "consoles" panel.
![issue_1](https://cloud.githubusercontent.com/assets/20865878/17684803/2f876512-6313-11e6-92c1-1c4cf4417df3.PNG)

**Expected Results:**
The device need been removed from the "consoles" panel.

**Comment by ddementieva** [comment]
@ZhangHangdong Bug confirmed.

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.

**Comment by bmicklea** [comment]
@ZhangHangdong - FYI, this is scheduled for the Aug-31 ARTIK IDE release.
