### ISSUE TITLE
C, C++, and Python projects do not have "hello world" demo.

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#110]
**Description of problem:**
C, C++, and Python projects do not have "hello world" demo.

**ARTIK IDE version:** artik-ide-1.0.0 
**ARTIK IDE install directory:** C:\artik-ide-1.0.0
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + samsung-artik-ide-latest.zip (2016-08-16)
**Browser:** Chrome

**Steps to Reproduce:**
1. Press "Workspace"
2. Press "Create Project"
3. Select "c/c++/java/nodejs/python" respectively
4. Input Name respectively
5. Press "Create" button

**Actual Results:**
Java, NodeJS projects have "hello world" demo; C, C++, and Python projects are empty.
![issue_5](https://cloud.githubusercontent.com/assets/20865878/17714003/9bdcf048-63b2-11e6-8f18-ce2fcedcc564.PNG)

**Expected Results:**
All projects have "hello world" demo.

**Comment by ddementieva** [comment]
@ZhangHangdong If you create project from scratch some project types indeed lack a source code.

If you create a project from Samples, you'll get a hello world demo. 

We'll mark it as improvement.
