### ISSUE TITLE
Fail to change project name 

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#111]
**Description of problem:**
When I change project name, the name no any change after press "OK". And, the project with old name still exist.

**ARTIK IDE version:** artik-ide-1.0.0 
**ARTIK IDE install directory:** C:\artik-ide-1.0.0
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + samsung-artik-ide-latest.zip (2016-08-16)
**Browser:** Chrome

**Steps to Reproduce:**
1. Right click any project (e.g. "abc")
2. Choose "Rename…"
![issue_6-1](https://cloud.githubusercontent.com/assets/20865878/17714607/57b986a8-63b5-11e6-9f7a-e642e7c24b35.PNG)
3. Input new name (e.g. "12345") in the dialogue, and press "OK" button
![issue_6-2](https://cloud.githubusercontent.com/assets/20865878/17714613/64e62d0e-63b5-11e6-8054-84133d73d673.PNG)

**Actual Results:**
The name of project no any change after press "OK"
![issue_6-3](https://cloud.githubusercontent.com/assets/20865878/17714684/970eef32-63b5-11e6-9a3f-2969aa60a89e.PNG)

And, if I reopen the workspace, I will see both "abc" (old name, cannot work) and "12345" (new name) projects
![issue_6-4](https://cloud.githubusercontent.com/assets/20865878/17714748/ed346e8c-63b5-11e6-9c2d-d0cc8c368f5f.PNG)

**Expected Results:**
project name changed successfully, and the page updated at the same time after press "OK"

**Comment by ddementieva** [comment]
@ZhangHangdong This is a known bug: https://github.com/eclipse/che/issues/1857
