### ISSUE TITLE
Create new file through "Assistant" -> "Find Action", show too many pages.

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#112]
**Description of problem:**
When I use "Assistant" -> "Find Action", find and open the page to create new file (any type: C, C++, Java...), It will show too many pages.

**ARTIK IDE version:** artik-ide-1.0.0 
**ARTIK IDE install directory:** C:\artik-ide-1.0.0
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + samsung-artik-ide-latest.zip (2016-08-16)
**Browser:** Chrome

**Steps to Reproduce:**
1.  On dashboard, press "Assistant" -> "Find Action"
2.  Input "new" as keyword for search.
3.  Double click any item to open the page which used for create new file.
![issue_7-1](https://cloud.githubusercontent.com/assets/20865878/17715974/991ceb02-63bb-11e6-8c4c-57e33558e9ec.PNG)
4. Create nothing, and close the page,
![issue_7-2](https://cloud.githubusercontent.com/assets/20865878/17715988/a4da2cc0-63bb-11e6-88e0-cce461898697.PNG)

**Actual Results:**
I must click "cancel" button many times. Because there are too many pages been created at step 3. 
![issue_7-3](https://cloud.githubusercontent.com/assets/20865878/17716483/b69e6bc2-63bd-11e6-8b05-47c7c5b2b698.PNG)

BTW, each operation (step 3) will cause the count of pages +1. 
For example:
create new file through "Find Action" at 1st time, pages = 5,
......                                                   at 2nd time, pages = 6,
......                                                   at 3rd time, pages = 7,
......

**Expected Results:**
 close the page just need to click "cancel" button once.

**Comment by ddementieva** [comment]
@ZhangHangdong Bug confirmed.
