### ISSUE TITLE
Duplicate “New Javascript file”menu in new file menu and without java file type

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#113]
**Description of problem:**
There is duplicate “New Javascript file”menu in “Project”->“New” and there is no java type menu in it.

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Chrome

**Steps to Reproduce:**
1. Press “Project”menu and then “New”.
2. The submenu of new file is shown

**Actual Results:**
1.There are two “JavaScript File” shown, the top one’s dialog displays inappropriate message -“new new”.
2. There is no java type menu.

**Expected Results:**
Developer can create java type project, so new file menu should contain java type file and duplicate new script menu should be removed.

**Comment by ddementieva** [comment]
@laralijuan Can you send a screenshot please? 

As to creating Java files, it's only possible in Java projects, while you've created (most probably) a C project.

**Comment by laralijuan** [comment]
@ddementieva  Yes, It is the Java project. And in Java project, C/C++/Python type file can also be created. And 
Please refer the below screenshots.
![image](https://cloud.githubusercontent.com/assets/20897963/17758622/86cd4ae6-6523-11e6-995b-f315fdf47a4e.png)
![image](https://cloud.githubusercontent.com/assets/20897963/17758643/a7fdc29a-6523-11e6-82aa-ce5e42882fa7.png)

**Comment by eivantsov** [comment]
@laralijuan No Java file is expected since you may only create java files in sc/main/java or whatevwer source folder is configured.

As to duplicate JavaScript file items in the menu, we will double check. Thanks

**Comment by laralijuan** [comment]
@eivantsov when focus on src, Java class/package can be created. But other irrelevant type file(C/C++/... for Java project) can also be created in src.
I suggest for different type project should have file type filter.

**Comment by ddementieva** [comment]
@laralijuan If you think it's a useful improvement, you can register an issue on that at https://github.com/eclipse/che/issues

**Comment by eivantsov** [comment]
@laralijuan i am going to close this one. Please open an issue in Che project if you haven't done so before.
