### ISSUE TITLE
Investigate possible integration with resin.io

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#114]
Investigate the mechanism resin.io uses to connect to boards and propose possible solutions regarding integration of resin.io with Artik IDE

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.

**Comment by eivantsov** [comment]
Proposed solution to Samsung team. Waiting for their feedback.
![resin](https://cloud.githubusercontent.com/assets/5337267/18160136/9358fff0-7034-11e6-9d65-e8592c3e0966.png)
