### ISSUE TITLE
Sub project “Download as zip…” will download the parent project

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#115]
**Description of problem:**
1. When download the sub project, the parent project will be downloaded too.
2. In “Workspace” and “Project” menu, there are same sub menu-”Download as Zip…” with same function.

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Chrome

**Steps to Reproduce:**
1. Create a project
2. Create 2 folders in the project and add 2 files to them seperately
3. Choose one of the created folders, “Project” -> “Convert To Project” -> choose a project type -> “Save”
![sgbtbq h](https://cloud.githubusercontent.com/assets/20897963/17767151/546c1134-6561-11e6-891d-9600b1abf1e4.PNG)
![s18uyx j](https://cloud.githubusercontent.com/assets/20897963/17767159/5897825c-6561-11e6-8a0e-2e6bc305bf7b.PNG)
4.  Choose the sub project
5.  Press “Project” -> “Download as a zip”. 

![image](https://cloud.githubusercontent.com/assets/20897963/17767172/7a15b43a-6561-11e6-91f2-615103455cc8.PNG)

![2](https://cloud.githubusercontent.com/assets/20897963/17767174/7ba55a4e-6561-11e6-932d-9c0be152d42d.png)

**Actual Results:**
The downloaded zip file contains parent project’s all the resources.

**Expected Results:**
1. The sub project should only contain its resources. (When right click the sub project, and "Download..." will only download the sub project's resources.)
2. I suggest the duplicated sub menu “Download as zip…” should only keep one.
![1](https://cloud.githubusercontent.com/assets/20897963/17767115/1f744262-6561-11e6-8d53-458e128f3fd6.png)

**Comment by ddementieva** [comment]
@laralijuan It's an expected behavior. 

To download some folder as a zip, right click on the chosen folder > Download...

**Comment by laralijuan** [comment]
@ddementieva The right click using mouse operation is right, the the menu operation is wrong.

**Comment by slemeur** [comment]
The "Download as Zip..." in the Project menu must only have the scope of the currently focused project only.

**Comment by slemeur** [comment]
Why is that closed?

**Comment by eivantsov** [comment]
@slemeur isn't it you who confirmed it's expected behavior?

**Comment by slemeur** [comment]
No. 

"Download as Zip..." in Project menu must only have the scope of the currently focused project only --> means that in this use case, only the project "2" is selected by the user, so only the project "2" should be in the Zip.

It should behave similarly to the other options of the "Project" menu:
- Configure Project --> Allow to configured only one project, the one selected
- Upload File --> Allow to upload a file in the selected folder from the tree

**Comment by eivantsov** [comment]
@slemeur project or folder?

**Comment by eivantsov** [comment]
Labeling as bug

**Comment by slemeur** [comment]
For the case of "Download as Zip", it should be the currently selected project and @laralijuan has converted the folder to be a project. 

Agree with you that if user wants to get only a folder, the contextual menu available with the right-click is handling that.
