### ISSUE TITLE
Cannot show the hidden file

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#116]
**Description of problem:**
Sub menu - “Show/Hide hidden files” doesn’t work. The hidden file cannot be shown.

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Chrome

**Steps to Reproduce:**
1. Create a project
2. Create a hidden file: .project
3. “Project” -> “Show/Hide hidden files”
4. Refresh the project.
5. The step 3 & 4 can be redone twice.
6. Download the project, the hidden file ".project"can be downloaded.

**Actual Results:**
The hidden file which exists actually cannot be shown in the project browser panel by using ”Show/Hide hidden files”.

**Expected Results:**
The hidden file can be shown by using “Show/Hide hidden files”.
The sub menu “Show/Hide hidden files” should be split. Show “Show hidden files” when they are hidden and Show “Hide hidden files” when they are shown.

**Comment by ddementieva** [comment]
@laralijuan We've checked it with Chrome and found no issues with showing hidden files. Take a look at the screenshot below:

![hidden-files](https://cloud.githubusercontent.com/assets/6860395/17766406/9f52e9a8-6533-11e6-8d07-9e34cdbc4353.png)

As to splitting Show / Hide hidden files menu, you can register a feature request on that at https://github.com/eclipse/che/issues

**Comment by laralijuan** [comment]
@ddementieva OK. I will ask ZhangHangdong help check this issue again. I tried some time, the hidden file never shown. My browser is Chrome too.

**Comment by ZhangHangdong** [comment]
@laralijuan I have checked it on my environment, The issue cannot be reproduced, “Show/Hide hidden files” function works well. I guess maybe some wrong with the browser cache, could you please clear the cache, or use other guy's PC to check the issue one more time. Thanks a lot!

**Comment by laralijuan** [comment]
@ZhangHangdong According your mentioned, it works well after clearing the browser cache.
