### ISSUE TITLE
Can not delete sample projects.

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#118]
**Description of problem:**
Can not delete sample projects.

**ARTIK IDE version:** artik-ide-1.0.0 
**ARTIK IDE install directory:** C:\artik-ide-1.0.0
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + samsung-artik-ide-latest.zip (2016-08-16)
**Browser:** Chrome

**Steps to Reproduce:**
1. Create a workspace
2. Create projects with any sample.
![issue_8-0](https://cloud.githubusercontent.com/assets/20865878/17794511/d33d0362-6564-11e6-936f-d456ccbfab52.PNG)
3. Delete the projects.

**Actual Results:**
The sample projects can not be deleted, other project (e.g. C, C++, Python) without sample can be deleted normally.
![issue_8-1](https://cloud.githubusercontent.com/assets/20865878/17794683/80d04f24-6566-11e6-96e2-cc828037d93b.PNG)
![issue_8-2](https://cloud.githubusercontent.com/assets/20865878/17794684/838103da-6566-11e6-9dbb-fe29528089fa.PNG)

**Expected Results:**
All projects can be deleted.

**Comment by eivantsov** [comment]
@ZhangHangdong I cannot reproduce this one. Are there maybe any additional steps to take?

Also, can you send a screenshot with browser dev console opened to see if there are exceptions and errors.

**Comment by ZhangHangdong** [comment]
@eivantsov I got the screenshot, hope it is useful. I think I can provide more such as system logs, if you tell me where they saved.
![issue_8-3](https://cloud.githubusercontent.com/assets/20865878/17827269/c4744f00-662e-11e6-9907-dc75ec22547c.PNG)

**Comment by eivantsov** [comment]
@ZhangHangdong the only suspicion that I have is that it is somehow related to VirtualBox - since windows directories get mounted into the VM and then in a container, there can be some sort of permissions issue.

Do you have a chance to try to reproduce this one on a Unix machine where the server runs natively? Meanwhile I will give it a shot on a Win 8 laptop with Vagrant and VBox. Thanks

**Comment by eivantsov** [comment]
@ZhangHangdong failed to reproduce on Win8

**Comment by ZhangHangdong** [comment]
@eivantsov sorry, I cannot find the logs. I think you are right, the issue is related with VBox. And I do more test below by using the terminal directly to delete the project file:
1. rm -rf artik-samples
2. all files under the "artik-samples" directory be deleted, except the "artik-samples" directory
3. "artik-samples" directory still cannot be deleted.
![issue_10](https://cloud.githubusercontent.com/assets/20865878/17910388/732f35e4-693d-11e6-917e-d5da0df81330.PNG)
