### ISSUE TITLE
[Critical] Can not open ARTIK terminal (new ARTIK board with empty "/root" directory)

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#119]
**Description of problem:**
[Critical] Can not open ARTIK terminal (new ARTIK board with empty "/root" directory)

**ARTIK IDE version:** artik-ide-1.0.0 
**ARTIK IDE install directory:** C:\artik-ide-1.0.0
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** VirtualBox + samsung-artik-ide-latest.zip (2016-08-16)
**Browser:** Chrome

**Steps to Reproduce:**
1. A new ARTIK board, nothing in "/root" directory
![issue_9-1](https://cloud.githubusercontent.com/assets/20865878/17795304/174b5d36-656c-11e6-9b2d-3b5a7a740955.PNG)
2. Create a workspace, and connect the ARTIK board through SSH.
![issue_9-2](https://cloud.githubusercontent.com/assets/20865878/17795323/59e94572-656c-11e6-9f38-485b0b45c25b.PNG)
3. Open the ARTIK terminal

**Actual Results:**
Can not open the ARTIK terminal. (all the time)
![issue_9-3](https://cloud.githubusercontent.com/assets/20865878/17795355/8df4074e-656c-11e6-9a9a-40fc43e5cf2f.PNG)

I guess maybe something wrong when copy files to /root/che/terminal. 
![issue_9-4](https://cloud.githubusercontent.com/assets/20865878/17795470/77614e1e-656d-11e6-861c-f162b9ccddc8.PNG)

**Expected Results:**
open ARTIK terminal successfully.

**Comment by eivantsov** [comment]
@ZhangHangdong when you `cd che` can you see terminal directory and some files in it?

What Artik board do you have? I cannot reproduce it with Artik 5 and 10.

**Comment by ZhangHangdong** [comment]
@eivantsov I can see terminal directory, but nothing in it. I tested on 520 and 710, both of them have the issue. 
![issue_9-5](https://cloud.githubusercontent.com/assets/20865878/17816509/5774832e-65ee-11e6-9065-edea6287a257.PNG)

BTW, I remove the exited che directory on the board firstly, and then start testing. And, I used VirtualBox to hold IDE server in my laptop (Win 7 64-bit).
![issue_9-6](https://cloud.githubusercontent.com/assets/20865878/17816675/47c5317a-65ef-11e6-97b9-825be2c5416e.PNG)

**Comment by eivantsov** [comment]
@ZhangHangdong looks like terminal files got copied into the wrong dir, although I don't know why it happened and cannot reproduce it with boards that I have. We have just got a few 720s, so it'll be a good chance to test Artik IDE with a clean board.

**Comment by ZhangHangdong** [comment]
@eivantsov the issue have been checked by laralijuan in the environment without virtualbox, and still not reproduce it. So I guess maybe the issue related with virtualbox. Could you please check it one more time by using virtualbox env. Thanks a lot.
