### ISSUE TITLE
Cannot delete the resources on ARTIK device during sync project files

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#123]
**Description of problem:**
Delete the projects or files in the IDE workspace, the corresponding sync projects or files on ARITK device cannot be removed.

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Firefox

**Steps to Reproduce:**
1. Install the rsync package on ARTIK Device, the synchronizing projects works.
2. Create two projects in the workspace and add several files to them.
![before delete](https://cloud.githubusercontent.com/assets/20897963/17921489/abc43754-6a0c-11e6-89fa-13c3dee16b87.PNG)
3. Delete one of the projects and delete the other project's one of the files in workspace.

**Actual Results:**
The rync process on ARTIK device cannot remove the deleted resources in workspace.
![after delete on artik](https://cloud.githubusercontent.com/assets/20897963/17921496/b20b631c-6a0c-11e6-95d3-9e3c738f529b.PNG)

The sync process on default machine is OK.
![after delete on default machine](https://cloud.githubusercontent.com/assets/20897963/17921502/bf04e174-6a0c-11e6-85a1-95eeb730463d.PNG)

**Expected Results:**
The sync process on ARTIK device cannot remove the deleted resources in workspace.

**Comment by eivantsov** [comment]
@laralijuan this commit should fix it - https://github.com/codenvy/dockerfiles/commit/c8ec5e52c36ce37a79628d9470e81b9bc52d641c

I have rebuilt codenvy/artik base image.

Can you run `docker pull codenvy/artik` and try it again?

**Comment by laralijuan** [comment]
@eivantsov yes, this issue is fixed. Thanks ~
