### ISSUE TITLE
The file can be synchronized from default machine to ARTIK device, but the conversely process cannot.

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#124]
**Description of problem:**
The file can be synchronized from default machine to ARTIK device, but the conversely process cannot.

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Firefox

**Steps to Reproduce:**

1. Install the rsync package on ARTIK Device, the synchronizing projects works.

2. Open default machine's terminal and input:
> _#cd /projects
> #touch default.txt_

3. Open ARTIK device's terminal, input:
> _#cd /root/projects
> #ls_ 

    the created file(default.txt) on default machine **can** be found.

4. Create a file at ARTIK device's "/root/projects/"
> _#touch artik.txt_

5. Open default machine's terminal, input :
> _#cd /projects
> #ls_ 

    the created file(artik.txt) on ARTIK device **cannot** be found.

**Actual Results:**
The file cannot be synchronized from ATRIK device to default machine.

**Expected Results:**
The file can be synchronized not only from default to ARTIK, but also from ARTIK to default.

**Comment by eivantsov** [comment]
@laralijuan this is expected behavior. It is not synchronization but replication of data. Projects in your workspace are replicated on the device. We do not run any scripts on the device as it is rather intrusive. Besides, it is in the developer workspace that changes to sources and binaries are made.
