### ISSUE TITLE
Synchronize function need to be improved, should not always show "rsync" errors

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#125]
**Description of problem:**
When I connect a new ARTIK board (have not installed "rsync" yet) to IDE, I always see the errors about "rsync" again and again, until I install it onto the ARTIK board.
![issue_12](https://cloud.githubusercontent.com/assets/20865878/17942706/5719adac-69ed-11e6-9e71-31714baf001d.PNG)

I think the synchronize function need to be improved, and I have 3 ideas:
1> add a switch on dashboard, let user decide whether synchronize automatically (switch on) or not (switch off)
2> install "rsync" onto ARTIK board automatically, if it have not been installed.
3> change the error to a helpful info, let users know how they need to do.

**Steps to Reproduce:**
1. Connect any ARTIK board without "rsync"
2. click "default" under "Consoles", then you can see the errors on its right panel.

**Actual Results:**
see error again and again, refer to the above picture.

**Expected Results:**
Any reasonable solution is welcome.

**Comment by eivantsov** [comment]
@ZhangHangdong yes, we will add rsync to list of software to be installed in a Dev profile

**Comment by eivantsov** [comment]
https://github.com/codenvy/artik-ide/pull/129 this pull request should at least make it easier to install rsync.

**Comment by eivantsov** [comment]
@ZhangHangdong proposed solution:

1. When connecting a device, check if rsync and gdbserver are installed and if not, suugest a user that these should be installed.

**Comment by ZhangHangdong** [comment]
@eivantsov Can we install rsync and gdbserver automatically? I guess maybe you are worry about the situation that no dnf configuration on user's board.
I propose that we install them once. Just install, do not need to do anything for dnf. If failed to install, then suggest user DIY.
