### ISSUE TITLE
Can not get and see the IP address through "adb devices" command

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#126]
**Description of problem:**
According to development backlog: DTIDE.07: Eclipse Che Discovery Service
and online documentation: [Connect-to-an-ARTIK-Device](https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started#4-Connect-to-an-ARTIK-Device)

I want to discover the IP address of my USB-connected (regular USB, not micro) ARTIK devices. All physical connection and software installation were done. But I found I cannot see the IP address through "adb devices"

**Steps to Reproduce:**
1. login in ARTIK board through micro-USB cable, and get IP for its wlan0 (192.168.1.96) (lo and p2p0 just for your reference)
![issue_13](https://cloud.githubusercontent.com/assets/20865878/17948907/d3cc54ac-6a07-11e6-896f-e14ad42b05ca.PNG)
2. Connect the ARTIK board with regular USB cable (ARTIK 520 used mini-USB cable)
3. Open "cmd" on my laptop (Win7), and run: "adb.exe devices -l"

**Actual Results:**
I got a number. not the IP address. 
![issue_13-1](https://cloud.githubusercontent.com/assets/20865878/17949061/8e82d2bc-6a08-11e6-9ccb-e03f63505ef3.PNG)

**Expected Results:**
I get and see the IP address (192.168.1.96)

**Comment by TylerJewell** [comment]
@ZhangHangdong - the docs for ARTIK IDE are about getting the IP address by using a terminal inside of your workspace.  You ran the `abd` command on your Windows DOS prompt, where configuration would be different.  Open the terminal in the workspace and follow the sequence of commands in the docs.

**Comment by ZhangHangdong** [comment]
@TylerJewell I get nothing in terminal.
![image](https://cloud.githubusercontent.com/assets/20865878/17949967/fc318a20-6a0c-11e6-848e-87e8e2b50560.png)

and the adbd service is working on the ARTIK board.
![image](https://cloud.githubusercontent.com/assets/20865878/17949972/0a30af98-6a0d-11e6-89f2-652ba7cea827.png)

**Comment by TylerJewell** [comment]
That is going to be hard to diagnose remotely - I just booted up a board, launched the Artik stack, connected over regular USB and then `abd devices` was able to work.  It does not work over micro-USB, however - so are you on a female:female connector?

**Comment by ZhangHangdong** [comment]
@TylerJewell Thanks a lot for your reply. I used mini-USB, and connected A520. I will do more testing and verification. 
And could you please show a screenshot under successful situation for me.

**Comment by TylerJewell** [comment]
I just took apart my artik board to mail to one of our PMs for more testing :), so cannot give you a screen shot.  But there isn't much to show. You should just get a list of IP addresses in the console.  The adb client is very simple, and gives minimal output. 

But this micro-USB limitation is a limitation of Google's ADB, it's not really a limitation of ARTIK IDE, Che or Samsung ARTIK board.

**Comment by eivantsov** [comment]
`adb devices` won't show IP it will list devices and their ID, we then extract those IDs and perform the following:

`adb -s $deviceId shell ifconfig $interfaceName` where $interfaceName is either `wlan0` or `eth0`

Since you use VirtualBox, can you ssh into a machine and look for the device there?

Another thing to try is to connect an Android based phone over USB and see if it is available in the workspace.

**Comment by eivantsov** [comment]
@ZhangHangdong any update on this?

**Comment by ZhangHangdong** [comment]
Sorry, I need more verification on different environment, to find out the key point of this functions.
I think for this issue, I think it has fixed. I can close this issue.
