### ISSUE TITLE
Debug function cannot connect the binary file built on ARTIK

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#127]
**Description of problem:**
When using debug, the binary file built on ARTIK cannot be connected by IDE.

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Chrome

**Steps to Reproduce:**

1. Make sure the ARTIK has installed rsync, gdb, gdb-gdbserver package.

2. Create a project with testing c type file in IDE

3. Open ARTIK device's terminal, compile & build the created project. And make sure the binary running well on ARTIK.
![binary](https://cloud.githubusercontent.com/assets/20897963/17954660/e7dc355a-6aae-11e6-8706-da1f20227621.PNG)

4. Start remote debug on ARTIK
   >#gdbserver :$port $binary 
   
   where $port is the port gdbserver will be running on, and the port the IDE GDB debugger will connect to, and $binary is a path to the binary being debugger.
![remote debug](https://cloud.githubusercontent.com/assets/20897963/17954719/5f9b9266-6aaf-11e6-898c-5fb6c8df68cb.PNG)

5. In IDE, "Run" -> "Edit Debug Configurations...", create a new GDB debug configuration, input the corresponding host, port and the binary path.

6. Start the debug, "Run" -> "Debug" ->{created debug name}

**Actual Results:**
IDE shows cannot connect to the debugging host, and the binary file cannot be found either.
![fail](https://cloud.githubusercontent.com/assets/20897963/17954712/502eb560-6aaf-11e6-8453-60d6b7e6b527.png)

For comparison, the same debugging process on the workspace's default machine is OK.
![success](https://cloud.githubusercontent.com/assets/20897963/17954953/3021d2b4-6ab1-11e6-99ff-51e888bc3ce7.png)

**Expected Results:**
Debug function should connect the binary file built on ARTIK successful.

**Comment by laralijuan** [comment]
The breakpoints don't work in IDE-1.0.0, the debugging cannot stop at the breakpoint. Does 1.0.0 provide this feature?

**Comment by eivantsov** [comment]
@laralijuan binary has to exist in the workspace as well. This is how GDB works.. binary should be both on the device and in the workspace.

**Comment by TylerJewell** [comment]
Is there anything that we can do to detect that the binary is not setup in both locations to provide a more helpful message to the user?  I am not sure there is but if we can add some sort of detector this may help many users avoid a common gotcha.

Also what browser is the OP using?  I notice the fonts are not displaying properly.

**Comment by laralijuan** [comment]
@eivantsov Yes, I have followed that doc. As your discription, the binary should be both on the device and workspace, it is still the problem. Because in #124 you know the binary built on ARTIK cannot be replicated to workspace and you said "Projects in your workspace are replicated on the device".  "Besides, it is in the developer workspace that changes to sources and binaries are made. "

But, the binary made in workspace cannot  run on ARTIK. So the remote debugging is still fail. For the binary made in workspace is x86's. 
![ws_binary_run_fail](https://cloud.githubusercontent.com/assets/20897963/17997310/5f980712-6ba0-11e6-9663-384a51f23989.PNG)

**Comment by laralijuan** [comment]
@TylerJewell the browser is Chrome. ARTIK IDE is running on Ubuntu. I use the Chrome on Win7.

**Comment by TylerJewell** [comment]
@ashumilova - is this a firefox issue, or is it perhaps due to a globalization setting on the host computer's OS affecting chrome?

**Comment by eivantsov** [comment]
@laralijuan how did you compile the binary?

I was able to compile the binary in a workspace and run a hello world on the device

This is my compile command:

`cd ${current.project.path} && $CC -g test.c`

Please note that I use `$CC` in my command which is https://github.com/eclipse/che-dockerfiles/blob/master/recipes/artik/Dockerfile#L10
![debug](https://cloud.githubusercontent.com/assets/5337267/18194460/69c8c23c-70ee-11e6-8918-1a9fee448573.png)

**Comment by laralijuan** [comment]
@eivantsov  Thank you. It runs well when using $CC or $CXX
