### ISSUE TITLE
Cannot remove the project backup from ARTIK after turned to production mode

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#128]
**Description of problem:**
The sync project backup cannot be removed automatically after turning the ARTIK to Production mode.

**ARTIK IDE version:** samsung-artik-ide-1.0.0 
**ARTIK IDE install directory:** ~/samsung-artik-ide-1.0.0/
**Docker version:** 1.12.0
**Java version:** 1.8.0_101
**Environment details:** Ubuntu 14.04 LTS + Docker + JDK+ samsung-artik-ide-1.0.0
**Browser:** Firefox

**Steps to Reproduce:**

1. Install the rsync package on ARTIK Device, make sure project sync works.

2. Create a testing project in workspace, the project can be found in ARTIK.
   
3. "ARTIK" -> "Profile" -> choose the connected ARTIK -> "Production"
   Confirm "Yes" and turning success.
 
![turn_to_production](https://cloud.githubusercontent.com/assets/20897963/17959729/d3ea3ecc-6ad4-11e6-9aee-a9f61005d995.PNG)

![turn_to_production_success](https://cloud.githubusercontent.com/assets/20897963/17959736/ddd93780-6ad4-11e6-9d35-d09f9f61c1a2.PNG)

**Actual Results:**
The sync project's backup is still remained on ARTIK
![still_remine_after_turn_to_production](https://cloud.githubusercontent.com/assets/20897963/17959747/eb81750a-6ad4-11e6-8495-7c5dc23ffd8f.PNG)

**Expected Results:**
The sync Project's backup is removed from ARTIK

**Comment by eivantsov** [comment]
@laralijuan this feature has not been yet implemented
