### ISSUE TITLE
Adapt Che Launcher for ARTIK IDE

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik-ide#130]
Add a job to our Jenkins system to:

1: Copy che.sh and che.bat from Che repo.
2: Place into artik-ide repo, but name it as artik-ide.sh and artik-ide.bat.
3. Inside the artik-ide.sh file, change the following default environment variables:
   DEFAULT_CHE_PRODUCT_NAME="ARTIK-IDE"
   DEFAULT_CHE_MINI_PRODUCT_NAME="artik"
   DEFAULT_CHE_SERVER_IMAGE_NAME="codenvy/artikide"
   DEFAULT_CHE_SERVER_CONTAINER_NAME="artikide"

**Comment by TylerJewell** [comment]
Unfortuantely we cannot add CI jobs that will do an auto-commit to the repository.  So I had to do a 1-time copy of the files.

https://github.com/codenvy/artik-ide/pull/131
