### ISSUE TITLE
Compile, Execute, Debug Simpler

### ISSUE THREAD

**Issue by ZhangHangdong** [codenvy/artik-ide#139]
Through my past testing, I think it is better for us to easier to compile/execute/debug codes. 
So I think:

**1. I need self-define commands, but I do not want write them for every projects, because most of them are same, I need a common/default configuration to compile/execute/debug codes easier and faster.**
![capture](https://cloud.githubusercontent.com/assets/20865878/18137278/91206be8-6f5c-11e6-9694-fb12e4c20cb7.PNG)

**2. If I wrote any source files on IDE dashboard and want to compile/run/debug them on my board, what I need to do are just:**
![capture](https://cloud.githubusercontent.com/assets/20865878/18137357/d506ac96-6f5c-11e6-83e1-4421f4af8153.PNG)

**Comment by TylerJewell** [comment]
@ZhangHangdong - this is super interesting.  @slemeur - would the "Play" and "Debug" buttons be restructured?  We could have a default play, but we could have a little drop-down indicator.  If you just click the button in the center, it will build.  However, if you click the drop-down indicator (much smaller), then we would drop down the list of commands, ability to edit commands.   We could do the same for the debug icon as well.

**Comment by TylerJewell** [comment]
@ZhangHangdong - if this improvement was made - this would probably need to be an upstream improvement into Eclipse Che - so we may need to push this issue over there for tracking.

**Comment by eivantsov** [comment]
@TylerJewell this is VERY Artik specific use case. Every compilation command is unique especially when it comes to apps that use Artik SDK.

This is what we are going to implement to make debug basically a 1 click operation - https://github.com/codenvy/artik-ide/issues/142

However, this is relevant for Artik only.

**Comment by eivantsov** [comment]
@ZhangHangdong as you can see commands to compile are different. Each sample has a different command since it uses different parts of the SDK.

We may create a universal command though to have `-I$CPATH/connectivity` `-I$CPATH/systemio` and so on.. this way every sample will compile. The the flow (for Artik) will be

1. Select source file - click compile
2. Select binary - click run on Device
3. Select binary - click Debug on Device

**Comment by TylerJewell** [comment]
@eivantsov - I am going to create a cross-cutting issue for Che as well.  While this came up in the context of ARTIK IDE, I think we could re-design the edit-commands drop down into a syntax that @ZhangHangdong is suggesting. Our behaviors would essentially be the same, but we can make a little UX design change that improves usability for new users to the system.

**Comment by ZhangHangdong** [comment]
@TylerJewell @eivantsov  Thank you very much! 

@eivantsov I understood that there ware some technical restrictions, make us had to do like this. But I think maybe we can do some workaround to reach it. 

1st, 
I do not think "Select binary" before "click run/debug" is good, because I need 4 steps (I think 3 is enough) to run/debug my codes.
1. Select source file
2. click compile
3. find binary and select it.
4. click run/debug
I think step 3 is unnecessary.

2nd,
Sorry that I am not familiar with compile process, but I am wonder that why we can not change 
`-I$CPATH/connectivity -I$CPATH/bluetooth -I$CPATH/lwm2m -I$CPATH/media -I$CPATH/sensor -I$CPATH/systemio -I$CPATH/wifi -I$CPATH/zigbee -I$CPATH/base ` 
to `$CPATH/*`.
Imagine, if users import some other libraries, they also need link every head files one by one themselves. If they just need to link the directory, not every files in it. They will more like the SW.

@TylerJewell @eivantsov In general, I think we can use some workaround to reach them.
For example, for the 2nd issue, give users a interface to set the directories which they want link all files in it. What we need to do are:
1. before compile, find all the directories user set.
2. loop each directory, find all files in it.
3. loop all files, and build the string to the format which used by compile.
4. integrate the string to compile command.
I think above are not hard to achieve, the 1st issue either.

**Comment by eivantsov** [comment]
@ZhangHangdong , selecting binary to run/debug is unavoidable. Don't you  select a binary to run locally? Of course, we may make an assumption that binary name is a.out and expect it to be in the project toot.

As to command that will be universal, I solved it. Not a problem anymore.

I think that selecting source file and binary  isn't difficult. It's quite intuitive too.

**Comment by eivantsov** [comment]
@ZhangHangdong would it help if a user can:

1. Configure compilation options (Project > Configure Compilation Options)
2. Configure binary name (Same menu)

The entire flow is:

1. A user creates a project
2. A user configures compilation options (optional. By default a project is configured to be using Artik SDK, and the default binary name is a.out)
3. A user selects source file and clicks Compile.
4. A user selects source file and clicks Run or Debug. Run or debug will recompile the project, send it to the device and execute/start gdbserver there.

So, essentially, it is a 2 click flow - select source file and compile or run/debug. Compilation options will be configurable. We have smth like that for Java project - a user can configure Java classpath and add custom jars.

**Comment by ZhangHangdong** [comment]
@eivantsov cool! it is great! I think your flow is more reasonable and will practical. Thank you very much. And I totally agree with you, this is not a problem. Anyone please change this issue to "enhancement".

**Comment by eivantsov** [comment]
@ZhangHangdong @TylerJewell yes, this will be scheduled for the next sprint. I expect that this will dramatically simplify com pile-run-debug flow, especially for new users (and sample apps)
