### ISSUE TITLE
Investigation: determine how to install needed RPMs on ARTIK device

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik-ide#148]
**Problem**
The ARTIK IDE starts and the workspace has everything needed, but the device is missing a set of RPMs as a result things won't run properly.

**Resolution**
Best solution: The ARTIK device would come with the full set of RPMs installed.
Better solution: The ARTIK developer profile includes the list of RPMs needed.
Okay solution: Document RPMs needed in the documentation.

**Comment by bmicklea** [comment]
@dangssi - can you or Greg please provide the list of RPMs?

**Comment by eivantsov** [comment]
@bmicklea I think we're taking care of this in https://github.com/codenvy/artik-ide/issues/125

I have tried a virgin device and it had everything except for rsync and gdb.

**Comment by bmicklea** [comment]
Closed as duplicate of #125
