### ISSUE TITLE
Rework artik-samples project in samples.json

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#162]
Artik samples repo is now a collection of folders with commands that are tied to folder names - https://github.com/codenvy/artik-ide/blob/master/assembly/assembly-main/src/assembly/templates/samples.json#L25-L163

With changes coming from a new  compile-run-debug flow, each sample program (folder) needs to be a project with own project attributes.

**Comment by vparfonov** [comment]
https://github.com/eclipse/che/issues/2937

**Comment by bmicklea** [comment]
@vparfonov was this included in 1.2 milestone?  If so please set milestone to 1.2
