### ISSUE TITLE
Build Eclipse che download Codenvy Maven repository always failed

### ISSUE THREAD

**Issue by lvbin0127** [codenvy/artik-ide#167]
Currently we are building local Maven repository, but we meet some issues: limited by network condition, Codenvy Maven dependency resource download always failed and it seems Codenvy Maven repository is not support breakpoint resume, so after trying download from Codenvy Maven repository, we are try to find another way to solve this issues, there is a solution for this issues, please give us some comments: 
    Is that possible for Codenvy to upload Codenvy Maven repository to mocrosoft onedrive cloud repository and we can download from the cloud repository? Currently, we need resource in the following url:http://maven.codenvycorp.com/content/repositories/public/com/codenvy/ (if we missing anything, please add). 
    If this can be realize, we will provide cloud website (username password) for you. So please give us some comments, thanks.
   ps: relative username and password please refer to mail that send to you .

**Comment by TylerJewell** [comment]
@eivantsov @riuvshin @bmicklea - FYI.

**Comment by ZhouAllan** [comment]
In order to develope Artik IDE, which packages we must download? "http://maven.codenvycorp.com/content/repositories/public/org/eclipse/che/" and "http://maven.codenvycorp.com/content/repositories/public/org/eclipse/artik/" are enough?

**Comment by eivantsov** [comment]
@lvbin0127 @ZhouAllan we'll be sending Samsung team zip with all deps.

**Comment by lvbin0127** [comment]
Thank you very much, so how can you send zip to us? method as we motioned in email (Onedirve Cloud)?

**Comment by eivantsov** [comment]
@lvbin0127 we'll send the url where you can download it and then use as you think appropriate.

**Comment by ZhouAllan** [comment]
The blocking issue is emergency, we have block download depedency resource for a long time, please provide url as soon as possible, thanks.

**Comment by eivantsov** [comment]
Zip sent via email

**Comment by lvbin0127** [comment]
Base on China network policy, we can not download resource from Google, so can you send deps to the cloud that we provide to you in the email?

**Comment by lvbin0127** [comment]
I have a question: is every artik-ide version corresponding one specific deps? if that, what aritk-ide version is corresponding to the deps that you send to us?

**Comment by bmicklea** [comment]
@lvbin0127 I have responded in email - the link you'd sent isn't working for me.

**Comment by lvbin0127** [comment]
I have download deps from Google cloud, thank you very much.
But today, i download che 4.7 and put deps into my local repository, when i use Eclipse to build Che (use offline mode) it always failed and display as follow:
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.eclipse.che:che-parent:4.7.0: Cannot access codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/) in offline mode and the artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:4.7.0 has not been downloaded from it before. and 'parent.relativePath' points at wrong local POM @ line 16, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.eclipse.che:che-parent:4.7.0 (/home/lvbin/artik_ide/che-4.7.0/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.eclipse.che:che-parent:4.7.0: Cannot access codenvy-public-repo (https://maven.codenvycorp.com/content/groups/public/) in offline mode and the artifact org.eclipse.che.depmgt:maven-depmgt-pom:pom:4.7.0 has not been downloaded from it before. and 'parent.relativePath' points at wrong local POM @ line 16, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
my colleages use command line also can't build based on offline mode, so can you give us some comments?

**Comment by slemeur** [comment]
The dependencies don't seem to be in the local Maven repository. 

Could you check what you have in you `.m2/org/eclipse/che/che-parent/` ?

**Comment by eivantsov** [comment]
@lvbin0127 did you try to build Artik IDE without Eclipse, just using Maven - `mvn clean install -o`.

Also, please note that the zip contains sources of other projects that need to be built in this particular order:

`che-parent`
`che-dependencies`
`che-lib` requires Go installed
`che` requires npm, bower and gulp installed
`arrtik-ide`

The best way to to that is to use a special Docker image with all the required software inside:

`docker run -ti -v ${unzipped-package}:/home/user/che-projects -v ${path-to-your-local-repo}:/home/user/.m2 codenvy/che-dev bash`

When in a container, navigate to `/home/user/che-projects` and `run mvn clean install` -o in each of them. When the compilation is done, you local maven repo will have all the missing artifacts.

The zip you have got has the pom that Eclipse is complaining about:

`codenvy-user@codenvy-office:~/Downloads/artik-sources-and-local-maven-repo/m2/repository/org/eclipse/che/depmgt/maven-depmgt-pom/4.7.0
codenvy-user@codenvy-office: ls
maven-depmgt-pom-4.7.0.pom maven-depmgt-pom-4.7.0.pom.sha1 _remote.repositories`

Also, you need to configure your Eclipse to be using the right Maven and the right Maven repo.

**Comment by bmicklea** [comment]
Closing as I believe this has been solved, if not please reopen with further details.
