### ISSUE TITLE
After create local Maven repository, why alway download dependency resource from Codenvy

### ISSUE THREAD

**Issue by ZhouAllan** [codenvy/artik-ide#171]
We have create local Maven repository and edit POM file in root of Artik ide project as follow: 

```
<repositories>
        <repository>
            <id>public</id>
            <name>Public Repositories</name>
            <url>http://109.105.112.252:8081/nexus/content/groups/public/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>public</id>
            <name>Public Repositories</name>
            <url>http://109.105.112.252:8081/nexus/content/groups/public/</url>
        </pluginRepository>
    </pluginRepositories>

```

But when we build Artik ide, it always download resource from Codenvy as follow:

```
[INFO] Downloading: http://109.105.112.252:8081/nexus/content/groups/public/org/eclipse/che/dashboard/che-dashboard-war/4.8.1-artik-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: http://109.105.112.252:8081/nexus/content/groups/public/org/eclipse/che/dashboard/che-dashboard-war/4.8.1-artik-SNAPSHOT/maven-metadata.xml (810 B at 15.5 KB/sec)
[INFO] Downloading: https://maven.codenvycorp.com/content/repositories/codenvy-public-snapshots/org/eclipse/artik/artik-ide-assembly-wsagent-server/1.2.0-SNAPSHOT/artik-ide-assembly-wsagent-server-1.2.0-20161011.174419-13.zip
[INFO] Downloading: https://maven.codenvycorp.com/content/repositories/codenvy-public-snapshots/org/eclipse/artik/artik-ide-assembly-wsagent-war/1.2.0-SNAPSHOT/artik-ide-assembly-wsagent-war-1.2.0-20161011.174424-13.war
```

after download from local Maven, it redirect to Codenvy, it there any place we are miss to edit?

**Comment by eivantsov** [comment]
@ZhouAllan where do you execute `mvn clean install`? In the root or `assembly` dir?

**Comment by ZhouAllan** [comment]
@eivantsov In the root folder of artik-ide

**Comment by eivantsov** [comment]
@ZhouAllan the zip package you have got container maven repo and projects that need to be built before you build artik IDE.

These are:

che-parent
che-lib
che-dependencies
che

Only after you have successfully built those projects, you can build Artik IDE.

Che and che-lib actually require Go, Node.js, npm, bower and gulp. So, the best way to use Docker to do that:

`docker run -ti  -v /path/to/projects:/home/user/projects-v $path/to/your/local/m2:/home/user/.m2 codenvy/che-dev bash`
`cd /home/user/projects`

Run `mvn clean install -DskipTests -Dskip-validate-sources -Dfindbugs.skip=true -Denforcer.skip=true` against each project in the above order.

**Comment by bmicklea** [comment]
Closing as this has been answered, if there are further questions please re-open.
