### ISSUE TITLE
Cannot open the machine's terminal at console panel

### ISSUE THREAD

**Issue by laralijuan** [codenvy/artik-ide#172]
**Description of problem:**
1. In ARTIK IDE, the created machine's terminal cannot be opened.
2. There is no "+" option in "Manage Artik Device" dialogue.

**ARTIK IDE version:** 
ARTIK IDE binaries: samsung-artik-ide-nightly (2016/10/13)
Docker version: 1.12.0
Java version: 1.8.0_101
Environment details: Ubuntu 14.04 LTS + Docker + JDK
Browser: Firefox

**Steps to Reproduce:**
1. get samsung-artik-ide-nightly.zip from https://install.codenvycorp.com/artik/
2. run bin/che.sh
3. create the workspace
4. open the workspce in IDE, console panel and manage artik device are empty.
![empty](https://cloud.githubusercontent.com/assets/20897963/19379374/404ecf62-9224-11e6-8317-80537dea24a7.PNG)
5. create the "test" project with hello.cpp file in IDE, console panel still empty.
![empty_create project](https://cloud.githubusercontent.com/assets/20897963/19407029/071444b2-92c8-11e6-9b89-85f3fceed266.PNG)
enter machine's docker containner, there is created "test" project.
![empty_container](https://cloud.githubusercontent.com/assets/20897963/19407030/17cbc2bc-92c8-11e6-884f-971e237eca38.PNG)

**Actual Results:**
Both the console panel and manage artik device dialogue display abnormal

**Comment by eivantsov** [comment]
@laralijuan can you give it a try in an incognito tab? I have downloaded the zip and run it - no issues found.

![image](https://cloud.githubusercontent.com/assets/5337267/19413809/3e28c3e6-92f6-11e6-8398-3e11b1604b0e.png)

**Comment by laralijuan** [comment]
@eivantsov I check it following your suggestion, It works well in incognito tab and chrome. 
ARTIK IDE 1.0.0 can display well in firefox's common tab, but why the subsequent version cannot?
