### ISSUE TITLE
Error message before specifying the file name while creating new file

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#187]
Right click the empty work space. **New** is enabled. Click any option "**New Java Script File/New C file" etc**. Error message appears in the alert before entering anything.
![error before typing](https://cloud.githubusercontent.com/assets/21373498/19779265/4435df24-9c35-11e6-8ea1-fcc105f86330.PNG)

**Comment by eivantsov** [comment]
@v-prabhu Labeling as enhancement.
