### ISSUE TITLE
Importing Zip folder imports only files, not the entire folder in the zip.

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#188]
Click on Project->Upload Folder. Pop up appears to add the zip file. Select a zip folder in the PC and Upload. Only the files under the folder will be added. Not the entire folder.

**Comment by eivantsov** [comment]
@v-prabhu this is expected behavior. Upload folder automatically unzips archive content. If you want to upload a zip file, you should upload file.
