### ISSUE TITLE
Default projects are not loaded in workspace until change the tabs

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#192]
![projects not loaded](https://cloud.githubusercontent.com/assets/21373498/19779466/1568e244-9c36-11e6-9310-4f30c5aba545.PNG)
Created work space does not have default project selected. User has to change the tabs to see the projects added.

**Comment by eivantsov** [comment]
@v-prabhu can you elaborate? Yes, project explorer is empty if there are no projects selected when starting a workspace.

**Comment by eivantsov** [comment]
@v-prabhu any update please? Can you give it a try with the latest version please?

**Comment by bmicklea** [comment]
@v-prabhu I'm closing the issue as it seems inactive, but if you're still having problems please re-open and explain whether you have a project in the workspace and send along the version of ARTIK (Help > About) and OS you're using.
