### ISSUE TITLE
Need to reconnect whenever artik board restarts

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#193]
Need to disconnect and connect the device everytime the artik board is switched on. Though IP address not changed.
![reconnetion](https://cloud.githubusercontent.com/assets/21373498/19779991/4eff46d6-9c38-11e6-90a7-7e5e8237a2cf.PNG)

**Comment by eivantsov** [comment]
@v-prabhu we treat Artik as a remote SSH machine. When a connection is lost, the  IDE cannot connect to a terminal. There's no automatic re-connect feature at the moment.

**Comment by v-prabhu** [comment]
OK. But at least developer should be intimated to reconnect the device rather than multiple error messages. And in the "Manage Artik Devices" screen, the label of the "Disconnect" button should change to "Connect".

**Comment by eivantsov** [comment]
@v-prabhu yes, it does make sense. Labeling it as enhancement.

**Comment by eivantsov** [comment]
https://github.com/codenvy/artik-ide/issues/203

Please, follow this one.
