### ISSUE TITLE
Update SDK and API ends up with error and already installed sdk is deleted

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#194]
Update SDK and API
![update failed](https://cloud.githubusercontent.com/assets/21373498/19780060/9b21aea0-9c38-11e6-82b5-86581b94ffe5.PNG)
 not working as expected. Click on Update SDK and API. Pop up appears with the installed SDK. Click on Install. Gives error and already installed SDK is deleted.

**Comment by eivantsov** [comment]
@v-prabhu these are commands that are executed on SDK update - https://github.com/codenvy/artik-ide/blob/master/plugins/plugin-artik-ide/src/main/resources/org/eclipse/che/plugin/artik/ide/updatesdk/installSdkOnDeviceCommand

Odds are that the updates repository was unavailable at the moment you ran SDK update. Can you repeatedly reproduce it?

Please, note that we have update codenvy/artik image with new artik.repo details, so you need to do the same on your device.

**Comment by v-prabhu** [comment]
I think the error might be because of the Wi-Fi network issue. Let me try with Ethernet connection. However, as a developer I do not wish my Instaleld SDK to be deleted if the Update fails in the beginning. Please let me know your thoughts on this.

**Comment by eivantsov** [comment]
@v-prabhu yes, good point. Let me think about it.
