### ISSUE TITLE
Save artik devices to user prefs

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#198]
Having updated to 5.0.x Artik devices are saved as long as the workspace lives. We should save devices into user prefs, so that workspace restart does not cause troubles for a user.

We need to save all info about the devices - hots, port, user, pass, replication folder.

**Comment by gazarenkov** [comment]
I'd say it has to be saved in project attributes instead.
AFAIK you avoid making dedicated PT (mixin) for Artik, I'd recommend to make it and store this kind of info there.

**Comment by eivantsov** [comment]
@gazarenkov Artik boards aren't bound to projects. Or workspaces. A developer needs his boards available for all projects. It's just connection information, device name etc.

**Comment by gazarenkov** [comment]
OK, I am not actually against of any preferences, just not sure this solution provides a good service in a case if you have more than one developers working on the same project b/c "development environment" (which part board is) may be not really "the same" for everybody.
