### ISSUE TITLE
artik-ide.sh start issue

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#200]
Hi,
I am trying to install and start IDE from a fresh system. However, when I try “./artik-ide.sh start” I am getting the error. Please see the image below for more info. Let me know how to resolve this. Tried googling and verified the user rights. Everything seems fine.
Please have a look and let me know if anything is missing.
![ide issue](https://cloud.githubusercontent.com/assets/21373498/19940242/35c7cab6-a0e9-11e6-8083-994b815d4f31.png)

**Comment by eivantsov** [comment]
```
# Stop all containers
docker stop $(docker ps -a -q)

# Delete all containers
docker rm -f $(docker ps -a -q)

# Delete all images
docker rmi -f $(docker images -q)
```

Then start again with the ARTIK IDE instructions from here:
https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started#1-get-artik-ide-cli

**Comment by TylerJewell** [comment]
This issue happened because the cli was still using the nightly che-launcher utility.  It was updated to assume a different type of Che server container which is not yet compatible with artik IDE.  We updated the cli to use tagged versions of Che launcher and server to fix this issue.
