### ISSUE TITLE
Is there any method to get full path of file on local host on function file upload?

### ISSUE THREAD

**Issue by lvbin0127** [codenvy/artik-ide#201]
When i use file upload function, i found it use FileUpload class, i want to get the full path of file on local host,such as  D:/test/test.txt, FileUpload class can't get the full path of file on local host based on security policy of browser, can you give me some comments about this issue?

**Comment by eivantsov** [comment]
@lvbin0127 JavaScript security does not allow doing that. At least, I do not see any obvious ways how this can be implemented.

**Comment by bmicklea** [comment]
Closing to clean up old questions.
