### ISSUE TITLE
Use OutputStream class, compile failed

### ISSUE THREAD

**Issue by lvbin0127** [codenvy/artik-ide#204]
I create a new class in ARTIK IDE project, in this class i use OutputStream class, it can work in a independent project, but when i put this class into ARTIK IDE project, compile failed and display:
[ERROR] Errors in 'jar:file:/home/lvbin/artik_ide/svn_checkout/svn/ArtikIDEDev/Code/00-Trunk/artik-ide-master/plugins/plugin-artik-ide/target/artik-ide-plugin-ide-1.2.0-SNAPSHOT.jar!/org/eclipse/che/plugin/artik/ide/installpkg/FileTransferClient.java'
[INFO]          [ERROR] Line 122: The method write(byte[], int, int) is undefined for the type OutputStream
[INFO]          [ERROR] Line 137: The method write(byte[], int, int) is undefined for the type OutputStream
[INFO]          [ERROR] Line 170: The method close() is undefined for the type OutputStream
[INFO]          [ERROR] Line 149: The method write(byte[], int, int) is undefined for the type OutputStream
[INFO]          [ERROR] Line 164: The method write(byte[], int, int) is undefined for the type OutputStream
[INFO]    [ERROR] Hint: Your source appears not to live underneath a subpackage called 'client'; no problem, but you'll need to use the <source> directive in your module to make it accessible
[INFO]                resolveResource(http://www.w3.org/TR/REC-xml, null, -//W3C//DTD SVG 1.1//EN, http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd, jar:file:/home/lvbin/maven-repository/org/eclipse/che/core/che-core-ide-app/4.8.1-artik-SNAPSHOT/che-core-ide-app-4.8.1-artik-SNAPSHOT.jar!/org/eclipse/che/ide/menu/submenu.svg)
[INFO]    Computing all possible rebind results for 'org.eclipse.che.ide.projecttype.wizard.categoriespage.CategoriesPageViewImpl.MainPageViewImplUiBinder'
can you tell me why?

**Comment by lvbin0127** [comment]
I use JDK version is 1.8.0_71,is that OK?

**Comment by lvbin0127** [comment]
for example, i need to use rt.jar, this jar is a JDK package, how to import this package to our project, because there is no JDK package in the MAVEN repository that you provide to us.

**Comment by lvbin0127** [comment]
I want to create a socket and operate it, how to do that?

**Comment by eivantsov** [comment]
@lvbin0127

**Comment by bmicklea** [comment]
Closing to clean up old questions.
