### ISSUE TITLE
Implement Run-Debug flow for Node.JS projects

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#217]
A user should be able to run and debug node.js apps on artik device.

Node command:

`node ${currently.selected.file}`

Debug command: @tolusha will share more details.

The issue is related to:

https://github.com/codenvy/artik-ide/issues/216

**Comment by svor** [comment]
Run flow was implemented and merged with [PR](https://github.com/codenvy/artik-ide/pull/242)
Debug feature still not implemented because had a bug on the node side (https://github.com/nodejs/node/issues/9854)
