### ISSUE TITLE
Can not delete or stop Workspace while starting workspace runtime

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#233]
Hi,
As a developer I would like to delete or stop the workspace while Starting Workspace Runtime (when downloading all the dependencies), for some reason. But there is no provision to stop the workspace initialization rather developer has to wait till the workspace daemon is up and running. Also, developer can not delete the workspace from the dashboard or Workspace tabs while Starting workspace runtime, though the Delete workspace is enabled.
![cant delete workspace while initializing](https://cloud.githubusercontent.com/assets/21373498/20777580/cb37c896-b71c-11e6-848a-dcc20d98546c.PNG)

**Comment by eivantsov** [comment]
@v-prabhu I do not believe Eclipse Che has this functionality. I will pass it over to management and dev team.

**Comment by bmicklea** [comment]
Closing as it will be tracked by this Che issue: https://github.com/eclipse/che/issues/3249
