### ISSUE TITLE
USB connected Artik devices are not recognized

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#235]
Hi,
I have connected my Artik module to my PC. But not able to see it in Manage Artik Devices window. As a developer, I want my Artik module to be detected automatically when connected by USB. Or the IDE should at least identify these modules and ask permission by he developer to start USB communication. Or the developer should be able to see the USB connected modules in Manage Artik Devices window.
![no usb](https://cloud.githubusercontent.com/assets/21373498/20777813/5340d984-b71e-11e6-9b66-e9e73d872abf.PNG)

**Comment by eivantsov** [comment]
@v-prabhu what OS do you use? And how did you start Artik?

**Comment by eivantsov** [comment]
@v-prabhu here's another issue - https://github.com/codenvy/artik-ide/issues/202
