### ISSUE TITLE
Create installer for Windows

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#237]
The installer should:

1. Provide Windows like installation experience
2. Install Docker (there will be different installers for Windows 10 and Windows 7,8)
3. Create a shortcut that will open Electron window asking a user for server connection details (local vs cloud)
4. If a local process is chosen check if artik-ide isn't running on localhost:8080. If not, start Artik IDE as a Docker container using `artik-ide.bat`
5. Everything that happens before the IDE is loaded should be logged in an electron window.

```
Checking for running Artik IDE instances...
Launching Artik IDE...
A running  instance of Artik IDE found. Connecting...
```

4. When Electron window is closed, and it is connected to a local process we should either ask a user if server should be shut down as well or just do it by default.

Repos to take a look at:

https://github.com/codenvy/che-installer
https://github.com/TylerJewell/che-electron

Electron Docs - http://electron.atom.io/docs/

**Comment by TylerJewell** [comment]
This issue does not match the Che specification that was developed for electron clients and installation.  This issue needs to conform to that approach and specification details before starting.

**Comment by vparfonov** [comment]
duplicate codenvy/artik-ide#281
