### ISSUE TITLE
Re-group compile, run and debug buttons

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#247]
Compile button should be to the right of delete button, near run.

![image](https://cloud.githubusercontent.com/assets/5337267/20966055/3eb3e3a4-bc81-11e6-9702-3823e3d8e0ac.png)

**Comment by svor** [comment]
![toolbr](https://cloud.githubusercontent.com/assets/1271546/21256753/d3241232-c37c-11e6-89f6-d5689bf410ae.png)
