### ISSUE TITLE
Debug button should be disabled for node.js projects

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#250]
Due to a bug in node.js it is currently impossible to use node.js debugger with a remote target. The following pull request should fix it:
https://github.com/nodejs/node/pull/10099

Until then, debug button for node.js projects should be disabled.

**Comment by bmicklea** [comment]
So that node PR was closed but not merged?

**Comment by lance** [comment]
Due to the nature of the process required to get code into Node.js core, PRs are not merged directly, but their contents are. In any case, the PR in question was merged here: https://github.com/nodejs/node/commit/6410534ec1062c8e3140bd3c2fc4f3d8a5bbdab7

**Comment by bmicklea** [comment]
Thanks for clarifying @lance - @vparfonov looks like you're unblocked.

**Comment by eivantsov** [comment]
We are bound to use 4.6.0 version which is the only version that Artik SDk officially supports.

**Comment by svor** [comment]
Actually, we can do this with 4.6.0. We need:
1. Clone source code of [Node.Js](https://github.com/nodejs/node); 
2. Checkout to necessary tag (4.6.0);
3. Make change which will fix a bug related to our [issue](https://github.com/nodejs/node/issues/9854). For this need to change only one line, this change already exists in Node.Js [master](https://github.com/nodejs/node/commit/6410534ec1062c8e3140bd3c2fc4f3d8a5bbdab7);
4. To build Node.Js from this source;
5. To install this version of Node.Js into device;
