### ISSUE TITLE
artik-ide start and ERROR !!! Error - Docker not installed properly issue

### ISSUE THREAD

**Issue by Connin** [codenvy/artik-ide#257]
Hello,
I am trying to follow 
https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started

But it gave me a lot of errors.. 

I got this error message by following this step (Win7 64-bit).
1. Install Docker.
2. Run Docker Quickstart Terminal and run docker run hello-world to verify it works.
3. Install Git for windows
4. Run Window cmd.
5.  window cmd, Type
set PATH=C:\Program Files\Git\bin\;%PATH%
6. Type
@FOR /f "tokens=*" %i IN ('docker-machine.exe env --shell cmd') DO @%i
7.Type
docker run hello-world 
and it works
8. Type
$ docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock eclipse/che start

And I got this message. kyle.bae is my username.

C:\Users\kyle.bae>docker run --rm -t -v /var/run/docker.sock:/var/run/docker.soc
k eclipse/che start
INFO: ECLIPSE CHE: Found image eclipse/che-server:latest
INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 5.0.0-M7
INFO: ECLIPSE CHE: Use: http://192.168.99.100:8080
INFO: ECLIPSE CHE: API: http://192.168.99.100:8080/swagger

9. Go to http://192.168.99.100:8080 and I verified that the link let me have Eclipse Che Workspace creation.
10. Type Bash and type those:

mkdir /c/Users/$USERNAME/artik-ide
cd /c/Users/$USERNAME/artik-ide
curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/artik-ide.bat > artik-ide.bat
curl -sL https://raw.githubusercontent.com/codenvy/artik-ide/master/artik-ide.sh > artik-ide.sh
mkdir /c/Users/$USERNAME/artik-ide/data

Verify all corresponding files are in artik-ide folder.

11. exit bash and type
set PATH=/c/Users/$USERNAME/artik-ide/;%PATH%
set CHE_DATA_FOLDER=/c/Users/%username%/artik-ide/data

12.OK, I think I did all to install ARTIK IDE.
If I type artik-ide start, I got this message.

C:\Users\kyle.bae>set PATH=/c/Users/$USERNAME/artik-ide/;%PATH%

C:\Users\kyle.bae>set CHE_DATA_FOLDER=/c/Users/%username%/artik-ide/data

C:\Users\kyle.bae>artik-ide start
'artik-ide' is not recognized as an internal or external command,
operable program or batch file.

13. If I cd to artik-ide and type artik-ide start, I got this error message.

C:\Users\kyle.bae>cd artik-ide

C:\Users\kyle.bae\artik-ide>artik-ide start
---------------------------------------
ERROR: !!!
ERROR: !!! Error - Docker not installed properly: \nCONTAINER ID        IMAGE
                    COMMAND                  CREATED             STATUS
     PORTS                              NAMES
c9feed3839d1        eclipse/che-server:latest   "/home/user/che/bin/d"   33 minu
tes ago      Up 33 minutes       8000/tcp, 0.0.0.0:8080->8080/tcp   che-server
ERROR: !!!
---------------------------------------

14. It says Docker not installed properly. But When I type docker run hello-world, I got this message.

C:\Users\kyle.bae\artik-ide>docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

It shows my docker install was done without an issue.

Ok. I think I missed something which is very simple stuff for experts.
It is my first experience to use bash cmd, cloud-based IDE, docker, or VM stuffs.
Can you help me to fix the error please? 

**Che version:**    5.0.0-M7  
**OS and version:** Window7  
**Docker version:** 1.12.3 
**Che install:**    docker  

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

Thanks.

**Comment by eivantsov** [comment]
@Connin can you enter bash and run:

docker rm -f $(docker ps -aq)

This command will remove all containers.

Then try executing bat file again.

**Comment by Connin** [comment]
Hello, thank you for reply. 
I tried your advise.

After Bash,

kyle.bae@STA119400 MINGW64 ~/artik-ide
$ docker rm -f $(docker ps -aq)
0eec5d557c4b
9c696950c406
f096a4507964
2379e1125f4f
d9ec57be7f0d
7c1a59bc822b
e76fb2f9efdd
25265d4dbaf4
f40fb08915e1
bc47fcc0ffa3
5676656304b6
1590321d8648
2fff0673433f
8c9d04e72c10
f78fd8964f04
5dfeeb21ad1a
b1cbf4701739
da38b09958c1
ba1f6d882365

kyle.bae@STA119400 MINGW64 ~/artik-ide
$ exit
exit

C:\Users\kyle.bae\artik-ide>artik-ide start
---------------------------------------
ERROR: !!!
ERROR: !!! Error - Docker not installed properly: \nCONTAINER ID        IMAGE
            COMMAND             CREATED             STATUS              PORTS
            NAMES
ERROR: !!!
---------------------------------------

It seems I still have the issue. Any other idea please?

Thanks.

**Comment by eivantsov** [comment]
@Connin I will give it a shot on my Win 8 laptop with Docker ToolBox installed.

It works for me on Win 10 though. I suspect that the problem is that `@FOR /f "tokens=*" %i IN ('docker-machine.exe env --shell cmd') DO @%i` enables docker of a current cmd session but artik-ide.bat calls artik-ide.sh that then checks if Docker is running (`docker ps`) and when `docker ps` is called the response isn't what we expect. Although in your case, the response is OK.

You may comment this like in artik-ide.sh and give it a shot again - https://github.com/codenvy/artik-ide/blob/master/artik-ide.sh#L915

**Comment by Connin** [comment]
Hello, thank you for your help.

I have modified artik-ide.sh code with notepad++.
I tried both ways and they gave me the same result:

C:\Users\kyle.bae\artik-ide>artik-ide start

C:\Users\kyle.bae\artik-ide>docker run --rm -t -v/var/run/docker.sock:/var/run/docker.sock eclipse/che start
INFO: ECLIPSE CHE: Found image eclipse/che-server:latest
INFO: ECLIPSE CHE: Starting container...
INFO: ECLIPSE CHE: Server logs at "docker logs -f che-server"
INFO: ECLIPSE CHE: Server booting...
INFO: ECLIPSE CHE: Booted and reachable
INFO: ECLIPSE CHE: Ver: 5.0.0-M7
INFO: ECLIPSE CHE: Use: http://192.168.99.100:8080
INFO: ECLIPSE CHE: API: http://192.168.99.100:8080/swagger

So,
 artik-ide start does not give any message including error message.

I opened http://192.168.99.100:8080
but I found ARTIK is still not in my workspace template:
![image](https://cloud.githubusercontent.com/assets/19319864/21123538/2605a476-c08e-11e6-92a5-72972f5de44a.png)

As you see, ARTIK is not in the template.
I believe the modified code let me bypass the error scenario but still the modified code does not get what it wants to finish the setup.

Any help would be appreciated.

Thanks!

**Comment by eivantsov** [comment]
What is the output from this command?

`C:\Users\kyle.bae\artik-ide>artik-ide start`?

The second command you ran is starting regular Che. So, it is expected not to have Artik stack there.

**Comment by Connin** [comment]
Hello,
I changed sh to 
if [ ! docker ps > /dev/null 2>&1 ]; then

Before I type 
@FOR /f "tokens=*" %i IN ('docker-machine.exe env --shell cmd') DO @%i
I got this:
C:\Users\kyle.bae\artik-ide>set PATH=C:\Program Files\Git\bin;%PATH%

C:\Users\kyle.bae\artik-ide>artik-ide start
INFO: Pulling image alpine:latest

C:\Users\kyle.bae\artik-ide>

![image](https://cloud.githubusercontent.com/assets/19319864/21153849/22091fb8-c121-11e6-8d90-b39d66671a8f.png)

Now, after I type
@FOR /f "tokens=*" %i IN ('docker-machine.exe env --shell cmd') DO @%i

I got no message.

C:\Users\kyle.bae\artik-ide>@FOR /f "tokens=*" %i IN ('docker-machine.exe env --shell cmd') DO @%i

C:\Users\kyle.bae\artik-ide>artik-ide start

C:\Users\kyle.bae\artik-ide>

Still, docker run hello-world works. 

![image](https://cloud.githubusercontent.com/assets/19319864/21154403/277b1cf6-c123-11e6-8156-ef017b69a496.png)

Thanks,

**Comment by Connin** [comment]
I have commented out check_docker by adding # and it also gave the same output

![image](https://cloud.githubusercontent.com/assets/19319864/21160734/bc5748a6-c13a-11e6-8b9f-c91b21269d4c.png)

**Comment by eivantsov** [comment]
@Connin I have just checked it on Windows 8.

```
C:\Users\Eugene\artik-ide>artik-ide start
INFO:
INFO: !!! Boot2docker detected - save workspaces only in %userprofile% !!!
INFO:
INFO: ARTIK-IDE: Found image codenvy/artikide:latest
INFO: ARTIK-IDE: Starting container...
INFO: ARTIK-IDE: Server logs at "docker logs -f artikide"
INFO: ARTIK-IDE: Server booting...
INFO: ARTIK-IDE: Booted and reachable
INFO: ARTIK-IDE: Ver: 5.0.0-M7-artik
INFO: ARTIK-IDE: Use: http://192.168.99.100:8080
INFO: ARTIK-IDE: API: http://192.168.99.100:8080/swagger
```

It looks like scripts do not get executed at all. But it did run for you when you first tried it. Can you remove them and pull the latest from the repo?

**Comment by eivantsov** [comment]
`artik-ide>docker run -p 8080:8080 -v /c/users/Eugene/workspace:/data --rm -t -v /var/run/docker.sock:/var/run/docker.sock codenvy`

**Comment by Connin** [comment]
Hello, Thank you for your help.

I believe it works with this command.
docker run -p 8080:8080 -v /c/users/Eugene/workspace:/data --rm -t -v/var/run/docker.sock:/var/run/docker.sock codenvy/artikide start

![image](https://cloud.githubusercontent.com/assets/19319864/21206295/de15478c-c215-11e6-926e-418bfc9cdb3e.png)

I got this after I connect to http://192.168.99.100:8080/

![image](https://cloud.githubusercontent.com/assets/19319864/21206210/5c506f6a-c215-11e6-8abb-4b62f549b4b9.png)

But how that command works?
I am not sure why it works this time. 

Thanks!

**Comment by eivantsov** [comment]
This command launches a different docker image - `codenvy/artikide`
