### ISSUE TITLE
Cannot run Docker using CLI in a container

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#288]
`docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/Eugene/workspace:/data codenvy/artik-cli:nightly start` results in an error:

`/scripts/cli.sh: line 25: CHE_DEVELOPMENT_MODE: unbound variable`

**Comment by benoitf** [comment]
Ok it's due to https://github.com/codenvy/codenvy/commit/2d03d3499cb83e6ea843440192e3814130dedebd
