### ISSUE TITLE
No provision to update the SDK to 1.1.3

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#295]
Hi,
I am trying to update the SDK of the Artik-530 module using IDE. However when I try to update, I am getting only 1.0 and 1.0.2 as option in the dropdown. There is no provision to update to 1.1.3.
Also, I was following the document available in "https://eclipse-che.readme.io/docs/samsung-artik-ide-getting-started#1-get-artik-ide-cli". But this link does not seem to be working. I just wanted to start testing IDE from scratch.

**Comment by eivantsov** [comment]
@v-prabhu is version 1.1.3 public? I do not think it is. Artik IDE checks for a publicly available repo and gets versions from there.

**Comment by eivantsov** [comment]
I am closing this issue since 1.1.3 isn't public yet, and Artik IDE looks for versions in a public repo
