### ISSUE TITLE
Creating workspace animation does not show up

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#300]
Hi, I am not getting the animation image while creating workspace is in progress. Following steps are followed.
1) Launch IDE in browser.
2) Create a new workspace.
3) While workspace creation is in progress, refresh the browser page.
4) Workspace animation image is missed and only a broken blinking image is shown.
![broken animation](https://cloud.githubusercontent.com/assets/21373498/22346487/2815b1fe-e3b9-11e6-82a5-57ea8e7e8ae7.PNG)

**Comment by v-prabhu** [comment]
Any attempt to launch IDE after this scenario, does not display the workspace creation in progress animation at all.

**Comment by eivantsov** [comment]
It must be a network issue. Can you make sure you disable firewall? Also, it's worth trying it in an incognito tab since some Chrome extensions may block JavaScript loading.

**Comment by eivantsov** [comment]
Closing the issue as it has been resolved.
