### ISSUE TITLE
"Update SDK and API" feature is not installing the APIs for compile and test

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#304]
When tried to update the SDK and APIs using IDE, the APIs required for compiling the source code and run the test cases are not being installed. 
We usually execute “dnf install libartik-sdk-tests”  to install the test files and dependent APIs. This would be followed by “dnf install libartik-sdk-systemio” to install other SDK dependencies. This is because usually the test examples execute using these APIs installed using “dnf install libartik-sdk-tests”. 
Just to verify, when you update SDK from IDE, 
•	You would not get any tests in /usr/lib/artik-sdk/tests/ directory
•	The header files would not be present at folders within “/usr/include/artik/”
•	You can not compile any code or run the test files.

In general, “libartik-sdk-tests-1.1-*.armv7hl.rpm” is the package that will install all these dependencies. This package would not be available when you do “dnf install libartik-sdk-systemio”.

**Comment by eivantsov** [comment]
I assign it to myself and will fix asap.

**Comment by v-prabhu** [comment]
@eivantsov With IDE 1.3.2 release, this issue does not seem to be working. Same comment as above still holds good.

**Comment by eivantsov** [comment]
@v-prabhu can you please elaborate? You need to update /etc/yum.repos/artik.repo in the workspace. Once done, you will see 1.1-3 version. And -tests package is installed now.

**Comment by eivantsov** [comment]
@v-prabhu please, take a look:

![image](https://cloud.githubusercontent.com/assets/5337267/22636416/8e618e0a-ec43-11e6-97d4-7d5ca1fcf045.png)

After a successful installation, I ran the following command on my Artik device:

```
[root@artik01 ~]# dnf list installed | grep libartik
libartik-sdk-base.armv7hl           1.1-3                             @artik-dev
libartik-sdk-bluetooth.armv7hl      1.1-3                             @artik-dev
libartik-sdk-connectivity.armv7hl   1.1-3                             @artik-dev
libartik-sdk-lwm2m.armv7hl          1.1-3                             @artik-dev
libartik-sdk-media.armv7hl          1.1-3                             @artik-dev
libartik-sdk-mqtt.armv7hl           1.1-3                             @artik-dev
libartik-sdk-sensor.armv7hl         1.1-3                             @artik-dev
libartik-sdk-systemio.armv7hl       1.1-3                             @artik-dev
libartik-sdk-tests.armv7hl          1.1-3                             @artik-dev
libartik-sdk-wifi.armv7hl           1.1-3                             @artik-dev
libartik-sdk-zigbee.armv7hl         1.1-3                             @artik-dev

```

**Comment by v-prabhu** [comment]
Header files to compile the code is not loaded under  /usr/include/artik/ directory. Probably you need to install test image also to get the required header files under /usr/include/artik/ directory.

**Comment by eivantsov** [comment]
Headers in a workspace are installed into a different directory.

**Comment by v-prabhu** [comment]
@eivantsov Iam taliking about connected artik module.

**Comment by eivantsov** [comment]
@v-prabhu i have taken this discussion to email.
