### ISSUE TITLE
"Connecting to Artik device" multiple alerts when the Artik module lost connectivity

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#305]
- Connect a artik module.
- After successful connection Turn off the Artik mdule or reset the Internet connection of the Artik module.
- Disconnect the Artik module from "Manage your artik devices" screen in IDE.
- Click Connect again.
- "Loading" text appears for some time and disappears.
- Click on Connect multiple times.
- IDE neither shows "Connection failed", rather displays multiple "Connecting to device" alerts. That will always be on screen.
![connecting multiple alerts](https://cloud.githubusercontent.com/assets/21373498/22392859/ec9ec354-e4b2-11e6-8129-2fd632749798.PNG)
![connecting multiple alerts-events](https://cloud.githubusercontent.com/assets/21373498/22392861/ef00932a-e4b2-11e6-9ba9-c9039b9a6061.PNG)
![capture2](https://cloud.githubusercontent.com/assets/21373498/22392873/0b6df3fe-e4b3-11e6-896f-65f968917572.PNG)

**Comment by eivantsov** [comment]
@v-prabhu after you turn off your Artik, how long did you wait to disconnect it? There is a utility in the workspace that checks availability of your Artik device. Once it's turned off, there should be a popup asking if you want to disconnect.

**Comment by eivantsov** [comment]
@v-prabhu I have tried to reproduce it on my side and I have got the following:

![image](https://cloud.githubusercontent.com/assets/5337267/22404086/35643e18-e632-11e6-917c-a0986d0e6ab7.png)

Can you reliably reproduce it? I ssh-ed into my Artik device and typed `reboot`. IN a few seconds I have got a popup in the IDE.

**Comment by eivantsov** [comment]
@v-prabhu we have identified what may cause the problem. A fix is available in the new version that we will release asap.

**Comment by eivantsov** [comment]
Fixed in 1.3.2
