### ISSUE TITLE
No provision to stop the port running gdb

### ISSUE THREAD

**Issue by v-prabhu** [codenvy/artik-ide#329]
After the issue https://github.com/codenvy/artik-ide/issues/328, try to start debugging of another file. IDE gives error "Can't bind address. Address already in use". But user does not get any information on how to end the session. Also, End Debug session option is disabled.

![cant bind address](https://cloud.githubusercontent.com/assets/21373498/22672596/d0c68d9a-ec89-11e6-9145-94c58ea04694.PNG)

**Comment by eivantsov** [comment]
@v-prabhu you need to stop previous debug command - the one from this screenshot - https://cloud.githubusercontent.com/assets/21373498/22672474/1423e99e-ec89-11e6-9393-6356853d92d6.PNG

Alternatively, you may kill a process by PID in Artik device.

**Comment by v-prabhu** [comment]
@eivantsov Looking at the screenshot in the issue, "End debug session" option is disabled. There is no way that I can stop the debugging. Also, referring to the screenshot, when I get this error, I will not know the PID to stop in the artik device.

**Comment by eivantsov** [comment]
@v-prabhu during a screenshare session we have confirmed the issue cannot be reproduced anymore. Closing it.

**Comment by v-prabhu** [comment]
1) Create a workspace with sample project "artik-samples"
2) Connect a Artik device
3) Select "ADC" from the project folder.
4) Compile and then debug on the connected device.
5) While debugging is in progress, end the debug session.
6) Try to debug again on the same device. Can not continue with debug with error "Address already in use".
 Please see the video below for reference:
https://youtu.be/RXPaMRFbjsY

**Comment by v-prabhu** [comment]
@eivantsov The issue exists with Mac installer.

**Comment by v-prabhu** [comment]
and also with all the platforms

**Comment by eivantsov** [comment]
The fix is in master, you can try it with nightly tag

**Comment by v-prabhu** [comment]
@eivantsov Nightly build works fine as expected. Thanks
