### ISSUE TITLE
 Investigate use of rsync instead of scp to replicate project files on the Artik device

### ISSUE THREAD

**Issue by vparfonov** [codenvy/artik-ide#90]
The device runs Fedora and so does the workspace. Rsync is available in both and does not require any fine tuning.
Below is a command that does the job:
`rsync -a --update --recursive --rsh="sshpass -p ${password} ssh -o StrictHostKeyChecking=no -l ${user}" /projects ${user}@${device-hostname}:${destination-path}`
We can grab all of the variables from device recipe.
It is possible to run this command according to a schedule (say, every 5 seconds). In addition, the command is invoked by file watcher events that detect changes.

**Comment by bmicklea** [comment]
@dkuleshov can you please add a status/... label to indicate where this issue is?
