### ISSUE TITLE
Artik Device logging

### ISSUE THREAD

**Issue by vparfonov** [codenvy/artik-ide#92]
It should be possible to get logs from device. At the moment it's not clear what exact logs, we may start with executing such a command as `journalctl -f`
This should be a button on consoles panel, next to terminal. We may also have it in Artik menu

**Comment by vparfonov** [comment]
@eivantsov : As discussed with Samsung, a user should be able to choose which file to tail.

**Comment by eivantsov** [comment]
@vparfonov it looks like using commands widget to tail logs is the best ways to go in this situation especially since we do not know what files to tail. I will update Artik stack with dmesg or a similar command to tail system logs.
