### ISSUE TITLE
Investigate how to connect local devices to the cloud

### ISSUE THREAD

**Issue by eivantsov** [codenvy/artik-ide#95]
It should be possible to connect local devices to a Codenvy cloud. It can be vpn or ssh tunneling. Summarize the most suitable options.

**Comment by JamesDrummond** [comment]
@eivantsov @skryzhny Let's chat about this when you get a chance. My thought has always been to use a separate "mount" container that would share a volume to the workspace. That way the workspace would not be required to have privileged access. The workspace would be passed the ssh login credentials of the mount container when it's created that can be displayed in the ssh console information. The mount container would limit ssh access to only sshfs access which is explain here [http://unix.stackexchange.com/questions/278489/how-to-make-ssh-account-capabele-to-only-sshfs-and-rsync](http://unix.stackexchange.com/questions/278489/how-to-make-ssh-account-capabele-to-only-sshfs-and-rsync).

**Comment by JamesDrummond** [comment]
@vparfonov Provide status label.

**Comment by eivantsov** [comment]
@JamesDrummond the goal of this task is to investigate how VPN can be used to connect local devices. How a mount container will help? We treat Artik as SSH machine that needs to have hostname/IP to connect to. @skryzhny has set up a test instance with OpenVPN running. We have connected to this VPN from Artik device which acquired a local IP relative to the instance. This IP was then used to connect to Artik board.

Blockers so far:

1. The IDE uses this local IP to try to connect to the terminal. As a result the connection fails.

Solution: make it possible to use 2 IPs when connecting to a device:

* VPN IP that the Tomcat will use to connect to a device
* Artik local IP that is reachable for the client browser

2. A service running on the device that will connect to a VPN and acquire a local IP

3. A service deployed with the workspace agent that will somehow grab this local IP (or perhaps several IPs) to display in the dropdown.

4. Some mechanism to prevent users from seeing other users' devices.

**Comment by skryzhny** [comment]
I tried PPTP servers but found that Artik devices lack needed kernel module, so PPTP client can't be used on Artik.
SSH is looks like more lite on resources but it really only port forwarding and we need to decide that ports are forwarded before starting connections.
Also take in account OpenVPN is supposed to connect networks, so it more suitable for our needs. Because we can mark connection from Artik to OpenVPN server as persistent, and managing software like NetworkManager will reconnect if connection was dropped. For SSH it's not the case, we need to ask user reconnect manually.

**Comment by TylerJewell** [comment]
@eivantsov - I think in your description, the device is the remote machine :).  So I think you are saying:
1: Service running on the device to start an OpenVPN server and advertise two IP addresses: <artik-ip> && <artik-terminal-ip>
2: A service deployed in a Che / Codenvy workspace agent, which can discover <artik-ip> and <artik-terminal-ip> for a particular "remote" device.
3: An OpenVPN client within the workspace to activate the connection and map all ports.
4: Some mechanism to limit discovery of other devices in a secure way.
