### ISSUE TITLE
Convert Vagrantfile to use Che Launcher syntax

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik-ide#99]
The current Vagrantfile uses the old Docker run syntax - it should be updated (if possible) to use the new Docker Launcher syntax.

**Comment by eivantsov** [comment]
@TylerJewell do we still need this? docker syntax is self sufficient I think

**Comment by TylerJewell** [comment]
No.  This should be removed for the Artik repository.  We will maintain vagrant on the core Che repo.

**Comment by TylerJewell** [comment]
Closing as won't fix - moved to docker launcher.
